{% set name = "interactivefitting" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/gabriele-vajente/interactivefitting/-/archive/{{ version }}/interactivefitting-{{ version }}.tar.gz
  sha256: 4d2d3bec492cb06a55eef3d4b870d9aa07f9810ce21e8f0a2efea3fcf6a64383

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - python-foton
    - pyqtgraph
    - pyqt

test:
  imports:
    - interactivefitting

about:
  home: https://git.ligo.org/gabriele-vajente/interactivefitting
  summary: 'Graphical user interface to fit transfer functions with VectFit3.'
  description:
    Graphical user interface to fit transfer functions with VectFit3. 
    And to allow tuning the result by manually moving
    or adding/removing poles and zeros.
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://git.ligo.org/gabriele-vajente/interactivefitting
  doc_url: https://git.ligo.org/gabriele-vajente/interactivefitting/-/blob/main/interactivefitting/TUTORIAL.md

extra:
  recipe-maintainers:
    - gabrielevajente
