{% set name = "interactivefitting" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/gabriele-vajente/interactivefitting/-/archive/{{ version }}/interactivefitting-{{ version }}.tar.gz
  sha256: 50b139b34497f43662db94a47d5f40c292d0b22821187491d7922eefb91b35be

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - python-foton
    - pyqtgraph
    - pyqt

test:
  requires:
    - python {{ python_min }}
  imports:
    - interactivefitting

about:
  home: https://git.ligo.org/gabriele-vajente/interactivefitting
  summary: 'Graphical user interface to fit transfer functions with VectFit3.'
  description: Graphical user interface to fit transfer functions with VectFit3. And to allow tuning the result by manually moving or adding/removing poles and zeros.
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://git.ligo.org/gabriele-vajente/interactivefitting
  doc_url: https://git.ligo.org/gabriele-vajente/interactivefitting/-/blob/main/interactivefitting/TUTORIAL.md

extra:
  recipe-maintainers:
    - gabrielevajente
